### PR TITLE
MAKER-548

### PR DESCRIPTION
**Pull request by noelpaz**
Added comments to indicate that mkdir, rmdir and remove return 0 not 1 on sucess with the explanation of the underlying Linux.

### CODE REVIEW

**Comment by noelpaz** [comment]
@bigdinotech  and @calvinatintel . Please review

**Comment by bigdinotech** [comment]
@calvinatintel looks good please merge

**Comment by calvinatintel** [comment]
@eriknyquist Wanna check for the syntax?

**Comment by noelpaz** [comment]
I only added comments

**Comment by eriknyquist** [comment]
@calvinatintel looks good to me. And, IMO there's not much point in manually monitoring for syntax stuff. Once the bot is ready, I'll do one big format, then the bot will do the work after that.

**Comment by calvinatintel** [comment]
@noelpaz Can you please change the commit message to be more descriptive?

**Comment by noelpaz** [comment]
@calvinatintel  . I followed the comment guidelines that I understood as per @eriknyquist  JIRA number on first  a blank line and then descriptive paragraph after that. IS there anything else I should be doing.

"MAKER-548

Added comments to indicate that mkdir, rmdir and remove return 0 not 1 on success with the explanation of the underlying Linux."

I imagine you want a short description on the first line.

Will need help with amending the commit message on this forks.

**Comment by calvinatintel** [comment]
Can you give me a short oneliner? I can amend it for you.

**Comment by noelpaz** [comment]
@calvinatintel  Amended comment. I also adding this on PR#31 for Edison

"MAKER-548  Added comments to explain return value of some SD functions

Added comments to indicate that mkdir, rmdir and remove return 0 not 1 on success with the explanation of the underlying Linux"

**Comment by calvinatintel** [comment]
Committed after an amend
https://github.com/01org/corelibs-galileo/commit/da12b3af257965e340a0b7a7465c1026ef660e9b

**Pull request closed without merging**
