### PR TITLE
Fix some issues with SD library

### PR DESCRIPTION
**Pull request by bigdinotech**
-added some missing implementations of write in the File class

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @kmsywula ready for code review

**Comment by bigdinotech** [comment]
- @eriknyquist

**Comment by eriknyquist** [comment]
@calvinatintel looks good. Reviewed & verified.

**Comment by SidLeung** [comment]
@calvinatintel Looks good.  Please merge.

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
