### PR TITLE
Cleanup for Galileo core-libs

### PR DESCRIPTION
**Pull request by bigdinotech**
Cleanup all warnings introduced with Arduino IDE 1.6.6+

### CODE REVIEW

**Comment by bigdinotech** [comment]
@kmsywula @SidLeung ready for review

**Comment by bigdinotech** [comment]
actually hold off a bit. I found an issue

**Comment by bigdinotech** [comment]
the issue is unrelated to my commits and seems to be an issue with Arduino 1.6.7 release
@kmsywula @SidLeung please go ahead and review

**Comment by kmsywula** [comment]
@calvinatintel code reviewed, please merge

**Pull request merged**
